### ISSUE TITLE
Nodes stats and other metrics from cluster APIs

### ISSUE THREAD

**Issue by webwurst** [braedon/prometheus-es-exporter#11]
I would like to get metrics for example for [cluster node stats](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/cluster-nodes-stats.html) so requesting `_nodes/stats` instead of `_all/_search`. Is that possible? Or planned?

**Comment by webwurst** [comment]
And also something like this: `/_stats/store` :-)

**Comment by braedon** [comment]
Hi @webwurst,

That's not on the roadmap for now - I intended this project for monitoring the data inside ES, rather than ES itself, and the JMX exporter can be used to get a lot of metrics out of ES (not sure if it covers all of the data in the endpoints you mentioned).

However, it shouldn't be that hard to do, and JMX is a little rubbish, so I'll have a think.

**Comment by braedon** [comment]
PR https://github.com/braedon/prometheus-es-exporter/pull/13

**Comment by braedon** [comment]
@webwurst @onibox FYI, pushed a beta docker image that includes these stats: `braedon/prometheus-es-exporter:0.3.0.beta1`

Check the updates to the README and tests for details, and let me know if you have any feedback.

**Comment by braedon** [comment]
Fixed in 0.3.0
