### ISSUE TITLE
More example for instrument metrics name and label on export.cfg

### ISSUE THREAD

**Issue by zanhsieh** [Braedon/prometheus-es-exporter#5]
Hi,

Just curious, what should i do if I'd like to let Prometheus metrics coming out with label or custom name?

To demo this, suppose I have following defined in exporter.cfg:

    [query_all]
    # How often to run this query.
    QueryIntervalSecs = 5
    # The indices to run the query on. Any way of specifying indices supported by your Elasticsearch version can be used.
    # This key is optional - if not specified, the default is '_all'.
    QueryIndices = _all
    # The search query to run.
    QueryJson = { "size": 0, "query": { "match_all": {} } }

    [query_login]
    QueryIntervalSecs = 20
    QueryIndices = _all
    QueryJson = { "query": { "query_string": { "query": "path: \"*login\" AND method: \"GET\" AND status:\"200\"" } } }

So Prometheus metrics come out with:

```
# HELP login_hits 
# TYPE login_hits gauge
login_hits 1756.0
...
...
# HELP all_hits 
# TYPE all_hits gauge
all_hits 18923.0
```

Now what should I change on "[query_login]" in order to get like below?

```
http_hits{path="/login", method:"GET", status="200"} 1756.0
```

Also, what should I change on exporter.cfg in order to get like this below?

```
avg_req_size{path="/login", method:"GET", status="200"} 1234.5
avg_resp_size{path="/login", method:"GET", status="200"} 1234.5
```

Thanks.

**Comment by Braedon** [comment]
Hi @zanhsieh,

There are basically two types of metrics the exporter can currently extract from responses. The first type is the basic count of hits - `<query_name>_hits` - which is what you're using in your example. There currently isn't support for labels on these kinds of metrics, as any information about the query (e.g. what status code it matches) can be encoded in the metric name (i.e. the query name). I'm open to adding support for this, but haven't found a use for it myself yet.

However, for the information you are extracting, you probably actually want to use the second type of metric. This is where metrics are built from ElasticSearch aggregations. If your docs have a numeric field that records the request size you can include an "average" aggregation in your query, giving you a metric that contains the average request size across the documents that matched your query (ditto with the response size).

Further, aggregations can be used to split your documents into "buckets". For example, you could relax your query to return all status codes, and use a "terms" aggregation to bucket the results by the status. This will give you a metric for each status code, with the corresponding status code in the "bucket" label.

You can then nest aggregations, either running functions like "average" on your buckets, or subdividing your buckets further (e.g. by method and path), or all of the above. Currently the bucket "names" for nested buckets are simply merged together into the single "bucket" label (basically because that's been sufficient for my use cases so far), so it can't produce the exact labels you're after, but I hope to improve that at some point. Let me know if you run into major issues with the current implementation, and I might be able to fast track that.

There are actually some examples for this kind of thing in the tests, so have a look there to get started. The more complicated stuff is towards the bottom. https://github.com/Braedon/prometheus-es-exporter/blob/master/tests/test_parser.py

I found this page from the Prometheus documentation helpful in working out how best to structure my metrics (and therefor the queries to produce them). https://prometheus.io/docs/practices/naming/

I hope that helps! Let me know if you have further questions.

Braedon
