### ISSUE TITLE
es index storage size is inconsistent

### ISSUE THREAD

**Issue by superfenv** [braedon/prometheus-es-exporter#65]
I use curl -X GET _cat/indices?v&s=index method and use exporter --es.indices to get elasticsearch_indices_store_size_bytes_total value is not the same?

**Comment by braedon** [comment]
Hi @superfenv, the metric values the exporter produces come directly from parsing elasticsearch APIs. Specifically, the `/_cluster/health`, `/_nodes/stats` and `/_stats` endpoints. If there is any discrepancy between these APIs and `_cat/indices`, it's a question for Elasticsearch, not this exporter.

If you can post a specific example of the metric you're looking at, and the mismatching `_cat/indices` output, I can point you at the exact Elasticsearch API field where the metric comes from.

**Comment by superfenv** [comment]
I wish you all the best and thank you for your reply
This problem is solved. As you said, it is not an es exporter problem. When
executing ES API queries, the storage type will be automatically converted.
Prometheus es exporter does not convert but in bytes, so it looks
inconsistent. In fact, it is converted after identical. Therefore, I have a
question, how to get the index value of storage in es exporter for
conversion (k/m/G..), instead of this
"(elasticsearch_indices_store_size_bytes_total / (1024*1024*1024))> 30"
Thank you.

Braedon Vickers <notifications@github.com> 于2020年6月18日周四 下午12:00写道：

**Comment by braedon** [comment]
Hi @superfenv, Prometheus metric values should always be in base units - bytes in this case - and it's up to clients to do any conversion. [See this section of the Prometheus documentation](https://prometheus.io/docs/instrumenting/writing_exporters/#naming):
> Metrics must use base units (e.g. seconds, bytes) and leave converting them to something more readable to graphing tools.

If you're writing queries manually rather than using client software, I'm not aware of any shortcuts to convert units, but that's really a question for the Prometheus community.
