### ISSUE TITLE
What is the recommended CPU and memory for this exporter?

### ISSUE THREAD

**Issue by vishrantgupta** [braedon/prometheus-es-exporter#84]
Hi @braedon, what is the recommended CPU and memory settings for this exporter?

**Comment by braedon** [comment]
Hi @vishrantgupta, it really depends on how many queries you're running, how many metrics they generate, and how big your cluster is (for cluster metrics).

For reference, I have an instance that runs a couple of queries against a small data set on a 3 node cluster - pretty minimal. It uses ~25MB of memory, and >1% CPU, so that's probably your lower limit.

I'd recommend trying it out and measuring its usage yourself for your setup.
