### ISSUE TITLE
Usage Problem?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [braedon/prometheus-es-exporter#93]
1.   Could you please update the helm repo to v3 ?
2.   Could you please provide a  grafana dashboard json ?
3.   Which version support the config reload ?

**Comment by braedon** [comment]
Hi @xuanyuanaosheng, I'll answer your questions in order:

1. As far as I'm aware, the existing helm repo works fine with helm v3 (that's what I'm running myself). Have you encountered a problem that requires updating it to v3 to work?

2. I haven't developed a general purpose Grafana dashboard, and don't have any plans to currently. If you'd like to contribute one I'd consider adding it as an example in the repo, or linking to it from the README. Please raise a separate issue or PR if so.

3. There's no support currently for reloading the config without restarting the process/container, and I don't have any plans to add it any time soon. I'm open to being convinced otherwise, however - see [the existing issue](https://github.com/braedon/prometheus-es-exporter/issues/46) on the topic if you'd like to argue for it. That issue also links to a workaround that could be useful to you if you're using k8s.

**Comment by xuanyuanaosheng** [comment]
@braedon  Thanks for your reply, I have test it, using the helm v3, it works fine.

**Comment by braedon** [comment]
Great, I'll leave the repo as-is for now since it works with helm v3. I'll probably upgrade it next time I have to change the chart.
