### ISSUE TITLE
Error while adding helm repo

### ISSUE THREAD

**Issue by kostas-rs** [braedon/prometheus-es-exporter#94]
Hi,

I have been using the exporter for a while now and its working very well. Today i tried to run update the repo using helm but im getting the below message:

`2021/05/05 14:46:26 ERROR: while adding repo [braedon]: Error: Looks like "https://braedon.github.com/helm" is not a valid chart repository or cannot be reached: Failed to fetch https://braedon.github.com/helm/index.yaml : 404 Not Found`

Thanks!

**Comment by braedon** [comment]
Darn, looks like I've been referencing braedon.github.com (old deprecated Github pages domain) in some places, instead of braedon.github.io (new Github pages domain)... My bad - I should have picked up on that before they stopped supporting the old one.

If you update your repo to https://braedon.github.io/helm (just add it again with the new URL) it should work.

I'll go through and update all the references...

**Comment by kostas-rs** [comment]
Ah that explains it, updated to the new repo and now it works like charm :)
Thanks!
